config/routes.rb
# == Route Map
#

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :simulation_steps

  resources :report_items

  get '/event_definitions/:id', to: 'simulations#event_definitions', as: 'event_definitions'
  get '/event_definition_monitor/:id', to: 'time_flow_monitors#event_definitions', as: 'event_definition_monitor'

  resources :projects do
    resources :simulations do
      member do
        get :start
        get :pause
      end
    end
    resources :reports do
      collection do
        get :event_stream_fields
      end
    end
    resources :time_flow_logs
    resources :event_stream_fields
    resources :event_streams do
      collection do
        get :saved_search
        get :external_data_sources
        get :simulations_workflow
        get :time_series
        get :metrics_workflow
      end
    end
    resources :alerts
    resources :time_flow_monitors, path: 'monitors' do
      member do
        get :start
        get :pause
        get :preview
      end

      collection do
        get :preview
      end
    end
    resources :splashes
    resources :datas do
      collection do
        post :set_event_stream
        post :search_results
      end
    end
  end

  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event_stream.rb
# == Schema Information
#
# Table name: event_streams
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  project_id  :bigint
#
# Indexes
#
#  index_event_streams_on_project_id  (project_id)
#
class EventStream < ApplicationRecord

  FIELD_TYPES = ['String', 'Integer', 'Float', 'Boolean', 'Timestamp', 'Date'].freeze
  DATA_TYPES  = ['Categorical', 'Continuous'].freeze
  LIST_ICONS = ['75.png', '76.png', '84.png', '78.png', '79.png', '80.png', '81.png', '82.png', '83.png'].freeze

  validates_presence_of :name
  with_options dependent: :destroy do |assoc|
    assoc.has_many :simulation_fields
    assoc.has_many :event_stream_fields
    assoc.has_many :event_streams
  end

  belongs_to :project, touch: true
  belongs_to :monitor_field, optional: true

  accepts_nested_attributes_for :event_stream_fields, reject_if: :all_blank, allow_destroy: true

  after_create :create_clickhouse_tables, unless: :skip_clickhouse_tables
  attr_accessor :skip_clickhouse_tables

  def create_clickhouse_tables
    p "Creating Clickhouse tables"
    KafkaClickhouse.create_tables self
    p "Clickhouse table creation complete"
  end

end

app/controllers/event_streams_controller.rb
class EventStreamsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_event_stream, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  def saved_search
  end

  def external_data_sources
  end

  def simulations_workflow
  end

  def time_series
  end

  def metrics_workflow
  end

  # GET /event_streams or /event_streams.json
  def index
    @event_streams = @project.event_streams
  end

  # GET /event_streams/1 or /event_streams/1.json
  def show
  end

  # GET /event_streams/new
  def new
    @event_stream = EventStream.new
    @event_stream.event_stream_fields.build
  end

  # GET /event_streams/1/edit
  def edit
  end

  # POST /event_streams or /event_streams.json
  def create
    p "In Create"
    p event_stream_params
    @event_stream = EventStream.new(event_stream_params)
    p "In Create"
    @event_stream.project_id = @project.id
    p "In Create"

    respond_to do |format|
      if @event_stream.save
        format.html { redirect_to project_event_streams_path(@project), notice: "Event stream was successfully created." }
        format.json { render :show, status: :created, location: @event_stream }
      else
        p @event_stream.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event_stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_streams/1 or /event_streams/1.json
  def update
    respond_to do |format|
      if @event_stream.update(event_stream_params)
        format.html { redirect_to project_event_streams_path(@project), notice: "Event stream was successfully updated." }
        format.json { render :show, status: :ok, location: @event_stream }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event_stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_streams/1 or /event_streams/1.json
  def destroy
    @event_stream.destroy
    respond_to do |format|
      format.html { redirect_to project_event_streams_path(@project), notice: "Event stream was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_stream
      @event_stream = @project.event_streams.find(params[:id])
    end

    def set_project
      @project = current_user_projects.find_by_id params[:project_id]

      return redirect_to projects_path unless @project.present?
    end

    # Only allow a list of trusted parameters through.
    def event_stream_params
      params.require(:event_stream).permit(:name,
        :description,
        event_stream_fields_attributes: [:id, :name, :description, :data_type, :stream_type, :required, :_destroy])
    end
end

app/helpers/event_streams_helper.rb
module EventStreamsHelper
end

app/views/event_streams/_event_stream_field_fields.html.erb
<div class="nested-fields pt-3 custom-table-new">
  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
        <div id="message" style="<%= f.object.errors[:name].present? ? '' : 'display:none;' %>">
          <%= f.object.errors[:name].first %>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
      </div>
    </div>

    <div class="col-md-2">
      <div class="dropdown">
        <%= f.select :stream_type, EventStream::FIELD_TYPES, {}, {class: 'form-select form-control'} %>
      </div>
    </div>

    <div class="col-md-2">
      <div class="dropdown">
        <%= f.select :data_type, EventStream::DATA_TYPES, {}, {class: 'form-select form-control'} %>
      </div>
    </div>

    <div class="col-md-1">
      <label class="check_box text-center d-inline">
        <%= f.check_box :required %>
        <span class="checkmark"></span>
      </label>
    </div>

    <div class="col-md-2">
      <%= link_to_remove_association(f, {class: 'remove_fields dynamic table_delete'}) do %>
        <%= image_tag('70.png') %>
        Delete
      <% end %>
    </div>
  </div>
</div>

app/views/event_streams/_event_stream_fields.html.erb
<div class="nested-fields pt-3 custom-table-new">
  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
        <div id="message" style="<%= f.object.errors[:name].present? ? '' : 'display:none;' %>">
          <%= f.object.errors[:name].first %>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
      </div>
    </div>

    <div class="col-md-2">
      <div class="dropdown">
        <%= f.select :stream_type, EventStream::FIELD_TYPES, {}, {class: 'form-select form-control'} %>
      </div>
    </div>

    <div class="col-md-2">
      <div class="dropdown">
        <%= f.select :data_type, EventStream::DATA_TYPES, {}, {class: 'form-select form-control'} %>
      </div>
    </div>

    <div class="col-md-1">
      <label class="check_box text-center d-inline">
        <%= f.check_box :required %>
        <span class="checkmark"></span>
      </label>
    </div>

    <div class="col-md-2">
      <%= link_to_remove_association(f, {class: 'remove_fields dynamic table_delete'}) do %>
        <%= image_tag('70.png') %>
        Delete
      <% end %>
    </div>
  </div>
</div>

app/views/event_streams/_form.html.erb
<%= form_with(model: [@project, @event_stream]) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
        <label><%= image_tag('69.png') %></label>
        <div id="message" style="<%= form.object.errors[:name].present? ? '' : 'display:none;' %>">
          <%= form.object.errors[:name].first %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_field :description, class: 'form-control', placeholder: 'Event Stream Description' %>
      </div>
    </div>

    <div class="col-md-12 mt-3">
      <div class="row event_table thead">
        <div class="col-md-2">Field Name</div>
        <div class="col-md-3">Description</div>
        <div class="col-md-2">Field Type</div>
        <div class="col-md-2">Data Type</div>
        <div class="col-md-1 text-center">Required</div>
        <div class="col-md-2 text-center">Actions</div>
      </div>
    </div>

    <div class="col-md-12">
      <div id="event_stream_fields">
        <%= form.fields_for :event_stream_fields do |ff| %>
          <%= render partial: 'event_streams/event_stream_fields', locals: {f: ff} %>
        <% end %>
      </div>

      <div class="links">
        <%= link_to_add_association(content_tag(:i, '', class: 'fa fa-plus') + '' + 'New Field', form, :event_stream_fields, class: 'import_btn mt-4 mb-3 mr-2') %>
      </div>
    </div>
  </div>

  <div class="row ">
    <div class="col-md-12">
      <div class="border_final mt-4">
        <%= form.submit "Submit", class: "custom_submit_button mt-5 mb-5" %>
      </div>
    </div>
  </div>
<% end %>

app/views/event_streams/edit.html.erb
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12 pb-3">
        <a href="<%= project_event_streams_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="new_event text-center pt-5">
          <h3 class="pb-4">Edit Event Stream</h3>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/event_streams/external_data_sources.html.erb
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <a href="<%= projects_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="event_stream_inner text-center">
          <%= image_tag('84.png') %>
          <h3>External Data Sources</h3>
          <p>No Data Sources are available.</p>
          <%= link_to 'Add Event Stream', new_project_event_stream_path(@project), class: 'project_btn mt-3' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/event_streams/index.html.erb
<% if @event_streams.present? %>
  <section class="event_stream">
    <div class="container">
      <div class="row"> 
        <div class="col-md-12">
          <div class="customer_value_exam row">
            <div class="col-md-1">
              <%= image_tag('71.png') %>
            </div>
            <div class="col-md-6">
              <h3><%= @project.name %></h3>
              <p><%= @project.description %></p>
            </div>
            <div class="col-md-2 text-right">
              <p class="pt-4">Owner: <%= current_user.full_name %></p>
            </div>

            <div class="col-md-3 text-right pt-1">
              <ul>
                <li>
                  <a href="#"><%= image_tag('74.png') %></a>
                </li>
                <li>
                  <a href="#"><%= image_tag('51.png') %></a>
                </li>
                <li>
                  <a href="#"><%= image_tag('72.png') %></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="border_bottom"></div>
        </div>

        <div class="col-md-12 mt-5">
          <table class="table event_stream"> 
            <thead>
              <tr>
                <td colspan="3">
                  <h4>Event Stream</h4>
                </td>
                <td colspan="1">
                  <form>
                    <input type="search" name="search" placeholder="Search">
                    <label><%= image_tag('85.png') %></label>
                  </form>
                </td>
              </tr>   
            </thead>
            <tbody>
              <% index = 0 %>
              <% @event_streams.each do |event_stream| %>
                <tr>
                  <td width="5%"><%= image_tag('Union.png', class: 'img_1') %></td>
                  <td width="5%"><%= image_tag(EventStream::LIST_ICONS[index], class: 'img_2') %></td>

                  <% index = index == 8 ? 0 : index + 1 %>

                  <td width="50%">
                    <div class="table_content">
                      <% if event_stream.description.present? %>
                        <h5 class="mb-"><%= event_stream.name %></h5>
                        <p class="mb-0"><%= event_stream.description %></p>
                      <% else %>
                        <h5 class="margin-15"><%= event_stream.name %></h5>
                      <% end %>
                    </div>
                  </td>
                  <td width="20%">
                    <div class="eye_inner">
                      <h6><%= event_stream.event_stream_fields.count %></h6>

                      <%= link_to edit_project_event_stream_path(@project, event_stream) do %>
                        <%= image_tag('eye.png') %>
                      <% end %>
                      <%= link_to edit_project_event_stream_path(@project, event_stream) do %>
                        <%= image_tag('edit.png', style: 'display: inline-block;') %>
                      <% end %>
                      <%= link_to project_event_stream_path(@project, event_stream), method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <%= image_tag('delete.png') %>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <center>
            <%= link_to 'Add Event Stream', new_project_event_stream_path(@project), class: 'project_btn mt-3 white_color_link align-items-center' %>
          </center>
        </div>
      </div>
    </div>
  </section>
<% else %>
  <!--Event Stream--> 
  <section class="event_stream">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="event_stream_inner text-center">
            <%= image_tag('event-icon.png') %>
            <h3>Event Streams</h3>
            <p>No Event streams available.</p>
            <%= link_to 'Add Event Stream', new_project_event_stream_path(@project), class: 'project_btn mt-3 white_color_link' %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--Event Stream-->
<% end %>

app/views/event_streams/metrics_workflow.html.erb
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <a href="<%= projects_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="event_stream_inner text-center">
          <%= image_tag('81.png') %>
          <h3>Metrics</h3>
          <p>No stream processors are available.</p>
          <%= link_to 'Add Event Stream', new_project_event_stream_path(@project), class: 'project_btn mt-3' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/event_streams/new.html.erb
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12 pb-3">
        <a href="<%= project_event_streams_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="new_event text-center pt-5">
          <h3 class="pb-4">New Event Stream</h3>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/event_streams/saved_search.html.erb
<!--Event Stream--> 
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <a href="<%= projects_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="event_stream_inner text-center">
          <%= image_tag('82.png') %>
          <h3>Saved Searches</h3>
          <p>No stream processors are available.</p>
          <%= link_to 'Add Event Stream', new_project_event_stream_path(@project), class: 'project_btn mt-3' %>
        </div>
      </div>
    </div>
  </div>
</section>
<!--Event Stream-->

app/views/event_streams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event_stream.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event_stream.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @event_stream.project %>
</p>

<%= link_to 'Edit', edit_event_stream_path(@event_stream) %> |
<%= link_to 'Back', event_streams_path %>

app/views/event_streams/simulations_workflow.html.erb
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <a href="<%= projects_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="event_stream_inner text-center">
          <%= image_tag('83.png') %>
          <h3>Simulations</h3>
          <p>No stream processors are available.</p>
          <%= link_to 'Add Event Stream', new_project_event_stream_path(@project), class: 'project_btn mt-3' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/event_streams/time_series.html.erb
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <a href="<%= projects_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="event_stream_inner text-center">
          <%= image_tag('81.png') %>
          <h3>Time Series</h3>
          <p>No stream processors are available.</p>
          <%= link_to 'Add Event Stream', new_project_event_stream_path(@project), class: 'project_btn mt-3' %>
        </div>
      </div>
    </div>
  </div>
</section>