config/routes.rb
# == Route Map
#

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :simulation_steps

  resources :report_items

  get '/event_definitions/:id', to: 'simulations#event_definitions', as: 'event_definitions'
  get '/event_definition_monitor/:id', to: 'time_flow_monitors#event_definitions', as: 'event_definition_monitor'

  resources :projects do
    resources :simulations do
      member do
        get :start
        get :pause
      end
    end
    resources :reports do
      collection do
        get :event_stream_fields
      end
    end
    resources :time_flow_logs
    resources :event_stream_fields
    resources :event_streams do
      collection do
        get :saved_search
        get :external_data_sources
        get :simulations_workflow
        get :time_series
        get :metrics_workflow
      end
    end
    resources :alerts
    resources :time_flow_monitors, path: 'monitors' do
      member do
        get :start
        get :pause
        get :preview
      end

      collection do
        get :preview
      end
    end
    resources :splashes
    resources :datas do
      collection do
        post :set_event_stream
        post :search_results
      end
    end
  end

  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/time_flow_monitor.rb
# == Schema Information
#
# Table name: time_flow_monitors
#
#  id             :bigint           not null, primary key
#  description    :text
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  project_id     :bigint           not null
#  sidekiq_job_id :string
#
# Indexes
#
#  index_time_flow_monitors_on_project_id  (project_id)
#
# Foreign Keys
#
#  fk_rails_...  (project_id => projects.id)
#
class TimeFlowMonitor < ApplicationRecord
  has_one :alert
  belongs_to :project
  has_one :monitor_field
  has_one :time_window
end

app/controllers/time_flow_monitors_controller.rb
class TimeFlowMonitorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, except: %i[ event_definitions ]
  before_action :event_streams, except: %i[ index destroy event_definitions ]
  before_action :set_time_flow_monitor, only: %i[ show edit update destroy start pause]

  # GET /time_flow_monitors or /time_flow_monitors.json
  def index
    @time_flow_monitors = @project.time_flow_monitors
  end

  # GET /time_flow_monitors/1 or /time_flow_monitors/1.json
  def show
  end

  # GET /time_flow_monitors/new
  def new
    @time_flow_monitor = TimeFlowMonitor.new
  end

  # GET /time_flow_monitors/1/edit
  def edit
    if @time_flow_monitor.monitor_field.present?
      @monitor_field = @time_flow_monitor.monitor_field
      @event_stream = @time_flow_monitor.monitor_field.event_stream
      @event_definitions = @time_flow_monitor.monitor_field.definitions
      @alert = @time_flow_monitor.alert
    end
  end

  # POST /time_flow_monitors or /time_flow_monitors.json
  def create
    @event_stream = EventStream.find(params[:event_stream])

    @time_flow_monitor = TimeFlowMonitor.new(time_flow_monitor_params)
    @time_flow_monitor.project = @project
    event_stream_fields = @event_stream.event_stream_fields
    definitions = []
    event_stream_fields.each_with_index do |e,i|
      definitions <<  {field: e.name, condition: params["operator-#{i}"], value:  params["value-#{i}"]}
    end
    timewindow = TimeWindow.create(direction: TimeWindow.directions[params["prev_next"].downcase.to_sym], duration: params["time-duration"], unit: TimeWindow.units[params["time_unit"].downcase.to_sym])
    @monitor_field = MonitorField.create(time_window_id: timewindow.id, time_flow_monitor: @time_flow_monitor, definitions: definitions, event_stream: @event_stream)
    @monitor_field.update(time_window: timewindow)
    @time_flow_monitor.update(monitor_field: @monitor_field)
    if params["alert"].present?
      Alert.create(name: params["alert"]["name"], description: params["alert"]["description"], time_flow_monitor_id: @time_flow_monitor.id, project_id: @time_flow_monitor.project_id, alert_condition: params["alert"]["alert_condition"], alert_condition_value: params["alert"]["alert_condition_value"]  )
    end
    respond_to do |format|
      if @time_flow_monitor.save
        format.html { redirect_to project_time_flow_monitors_path(@project), notice: "Time flow monitor was successfully created." }
        format.json { render :show, status: :created, location: @time_flow_monitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_flow_monitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_flow_monitors/1 or /time_flow_monitors/1.json
  def update
    MonitorField.where(time_flow_monitor_id: @time_flow_monitor.id).destroy_all if @time_flow_monitor.present?
    TimeWindow.where(monitor_field: @monitor_field.id).destroy_all if @monitor_field.present?
    Alert.where(time_flow_monitor_id: @time_flow_monitor.id).destroy_all if @time_flow_monitor.present?

    @event_stream = EventStream.find(params[:event_stream])
    event_stream_fields = @event_stream.event_stream_fields

    definitions = []
    event_stream_fields.each_with_index do |e,i|
      definitions <<  {field: e.name, condition: params["operator-#{i}"], value:  params["value-#{i}"]}
    end

    timewindow = TimeWindow.create(direction: TimeWindow.directions[params["prev_next"].downcase.to_sym], duration: params["time-duration"], unit: TimeWindow.units[params["time_unit"].downcase.to_sym])
    @monitor_field = MonitorField.create(time_window_id: timewindow.id, time_flow_monitor: @time_flow_monitor, definitions: definitions, event_stream: @event_stream)
    @monitor_field.update(time_window: timewindow)
    @time_flow_monitor.update(monitor_field: @monitor_field)
    if params["alert"].present?
      Alert.create(name: params["alert"]["name"], description: params["alert"]["description"], time_flow_monitor_id: @time_flow_monitor.id, project_id: @time_flow_monitor.project_id, alert_condition: params["alert"]["alert_condition"], alert_condition_value: params["alert"]["alert_condition_value"]  )
    end
    respond_to do |format|
      if @time_flow_monitor.update(time_flow_monitor_params)
        format.html { redirect_to project_time_flow_monitors_path(@project), notice: "Time flow monitor was successfully updated." }
        format.json { render :show, status: :ok, location: @time_flow_monitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_flow_monitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_flow_monitors/1 or /time_flow_monitors/1.json
  def destroy
    @time_flow_monitor.destroy
    respond_to do |format|
      format.html { redirect_to project_time_flow_monitors_path(@project), notice: "Time flow monitor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def start
    job = Sidekiq::Cron::Job.new(name: 'CreateAlertWorker - every 10s', cron: '*/10 * * * * *', args: @time_flow_monitor.id, class: 'CreateAlertWorker')
    if job.valid?
      @time_flow_monitor.update(sidekiq_job_id: 1)
      job.save
      job.enable!
    else
      puts job.errors
    end
    render json: {
      status: "scheduled"
    }
  end

  def pause
    job = Sidekiq::Cron::Job.find('CreateAlertWorker - every 10s')
    @time_flow_monitor.update(sidekiq_job_id: nil)
    job.disable!
    render json: {
      status: "disabled"
    }
  end

  def event_definitions
    @event_stream = EventStream.find(params[:id])
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def preview
    @event_stream = EventStream.find(params[:event_stream_id])
    # build monitor fields
    event_stream_fields = @event_stream.event_stream_fields
    definitions = []
    event_stream_fields.each_with_index do |e,i|
      definitions <<  {field: e.name, condition: params["operator-#{i}"], value:  params["value-#{i}"]}
    end

    # build monitor fields

    @response = KafkaClickhouse.get_all_data(@event_stream)

    @rows = @response.rows
    @columns = @response.columns
    @total_records = @rows.count

    #filter
    data = []
    @rows.each do |r|
      data << Hash[@columns.zip(r)]
    end
    @rows = (MonitorField.filter_simulation_data(data, definitions)).collect { |t| t.values}

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_flow_monitor
      @time_flow_monitor = @project.time_flow_monitors.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_flow_monitor_params
      params.require(:time_flow_monitor).permit(:name, :description)
    end

    def event_streams
      @event_streams ||= @project.event_streams.pluck(:name, :id)
    end
end

app/helpers/time_flow_monitors_helper.rb
module TimeFlowMonitorsHelper
end

app/views/time_flow_monitors/_event_definition_fields.html.slim
- event_stream.event_stream_fields.each_with_index do |esf,i|
  tr
    td
      .no-gutters
        = text_field_tag esf.name, '', class: 'form-control', placeholder: esf.name
    td
      .no-gutters
        = select_tag "operator-#{i}", options_for_select(ApplicationRecord::SQL_OPERATORS), class: 'form-control'
    td
      .no-gutters
        input.form-control[type="text" placeholder="Value" id="value#{i}" name="value-#{i}"]
    td

app/views/time_flow_monitors/_form.html.erb
<%= form_with(model: [@project, @time_flow_monitor], id: "monitors" ) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_field :name, class: 'form-control', placeholder: 'Monitor Name' %>
        <div id="message" style="<%= form.object.errors[:name].present? ? '' : 'display:none;' %>">
            <%= form.object.errors[:name].first %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_field :description, class: 'form-control', placeholder: 'Monitor Description' %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="table-responsive mt-4 custom_table monitor ">
        <table class="table">
          <thead>
            <tr>
              <th colspan="4" class="form_img">
                <form>
                  <input type="search" name="search" placeholder="Search">
                    <%= image_tag('Vector.png') %>
                </form>
              </th>
            </tr>
          </thead>
          <tr>
            <td colspan="3">
              <h4  class="text-left pt-3">Time Window</h4>
            </td>
            <td colspan="2" align="right">
              <ul class="nav nav-tabs float-right " id="myTab" role="tablist">
                <li class="nav-item">
                  <a class="nav-link " id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"> Filters</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Aggregations</a>
                </li>
              </ul>
            </td>
          </tr>
          <tr>
            <td width="30%">
            <div class="form-group">

            <select class="form-control form-select" id="prev_next" name ="prev_next">
              <option value="">Select</option>

              <option value="Next" selected="<%= ' selected' if @monitor_field&.time_window&.direction == :next %>">Next</option>
              <option value="Prev" selected="<%= ' selected' if @monitor_field&.time_window&.direction == :prev %>">Prev</option>
            </select>
            </div>
            </td>
            <td width="20%">
              <div class="form-group">
                <input type="text"  id ="time-duration" name ="time-duration" value ="<%=@monitor_field&.time_window&.duration %>" class="form-control" value="5">
              </div>
            </td>
            <td width="20%">
            <div class="form-group">
            <select class="form-control form-select" id="time_unit" name="time_unit">
                <option value="">Select</option>
                <option value="Seconds" selected="<%= ' selected' if @monitor_field&.time_window&.direction == :seconds %>"> Seconds</option>
                <option value="Minutes" selected="<%= ' selected' if @monitor_field&.time_window&.unit == :minutes %>"> Minutes</option>
                <option value="Hours" selected="<%= ' selected' if @monitor_field&.time_window&.unit == :hours %>">Hours</option>
                <option value="Days" selected="<%= ' selected' if @monitor_field&.time_window&.unit == :days %>">Days</option>
                <option value="Weeks" selected="<%= ' selected' if @monitor_field&.time_window&.unit == :weeks %>">Weeks</option>
                <option value="Months" selected="<%= ' selected' if @monitor_field&.time_window&.unit == :months %>">Months</option>
                <option value="Years" selected="<%= ' selected' if @monitor_field&.time_window&.unit == :years %>">Years</option>
              </select>
            </div>
            </td>
            <td width="30%"></td>
          </tr>
          <tr class="pt-3">
            <td colspan="3">
              <h4  class="text-left pt-3">Search</h4>
            </td>
            <td colspan="2" align="right"></td>
          </tr>
          <tr>
            <td width="30%">
              <div class="form-group">
                <%= select_tag :event_stream, options_for_select(@event_streams, [@event_stream&.id]), id: 'event_stream_monitor', class: 'form-control form-select', prompt: 'Select' %>
              </div>
            </td>
          </tr>
          <tbody id="event_definition_fields">
            <% if @event_definitions.present?%>
              <% @event_definitions.each_with_index do |esf,i|%>
                <tr>
                  <td>
                    <div class="no-gutters">
                      <%= text_field_tag esf["field"], '', class: 'form-control', placeholder: esf["field"] %>
                    </div>
                  </td>
                  <td>
                    <div class="no-gutters">
                      <%= select_tag "operator-#{i}", options_for_select(ApplicationRecord::SQL_OPERATORS, [esf["condition"]]), class: 'form-control' %>
                    </div>
                  </td>
                    <td>
                    <div class="no-gutters">
                      <input type="text" placeholder="Value" id="value-<%=i%>" value="<%=esf["value"]%>" class="form_control" name="value-<%=i%>" >
                    </div>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= image_tag('91.png', class: 'back_img') %>
      <a href="javascript:void(0);" data-turbolinks= "false" class="project_btn mt-3 mb-3" id="preview_btn">Preview</a>
      <%= image_tag('91.png', class: 'back_img', id: 'preview_arrow', style:'display:none') %>
    </div>
  </div>
  <div class="row" id="preview_table">
  </div>
  <div class="row" id="alert_table" style="display:none">
    <div class="col-md-12">
      <div class="table-responsive mt-3 custom_table monitor alert_config">
        <table class="table">
          <thead>
            <tr>
              <th colspan="4" class="form_img">
                <h5 class="mb-0">Alert Configuration</h5>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colspan="3">
                <h4  class="text-left pt-3">Condition</h4>
              </td>
              <td colspan="2" align="right">
                <ul class="nav nav-tabs float-right " id="myTab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link " id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"> Condition</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Alerts Dteails</a>
                  </li>
                </ul>
              </td>
            </tr>
            <tr>
              <td width="50%">
              <div class="form-group">
              <select class="form-control form-select" id="alert[alert_condition]" name="alert[alert_condition]">
                <option value="Number Of Results Greater Than">Number Of Results Greater Than</option>
                <option value="Sum Of Column Greater Than">Sum Of Column Greater Than</option>
                <option value="Average Of Column Greater Than">Average Of Column Greater Than</option>
                <option value="Minimum Of Column Greater Than">Minimum Of Column Greater Than</option>
                <option value="Maximum Of Column Greater Than">Maximum Of Column Greater Than</option>
                <option value="Column Contains Of Column Greater Than">Column Contains Of Column Greater Than</option>
              </select>
              </div>
              </td>
              <td></td>
            </tr>
            <tr>
              <td width="50%">
                <div class="form-group">
                  <input type="text" class="form-control" value="<%=@alert&.alert_condition_value %>" id="alert[alert_condition_value]" name="alert[alert_condition_value]">
                </div>
              </td>
              <td></td>
            </tr>
            <tr>
              <td width="50%">
                <div class="form-group" style ="text-align:left">
                  <div class="input string required"><label for="alert_title" class="string required"><abbr title="required"></abbr>Name</label><input type="text" value ="<%=@alert&.name %>" size="30" required="required" name="alert[name]" maxlength="255" id="alert_name" class="string required"></div>
                  <div class="input string required"><label for="alert_description" class="string required"><abbr title="required"></abbr>Description</label><input type="text" value ="<%=@alert&.description %>" size="30" required="required" name="alert[description]" maxlength="255" id="alert_description" class="string required"></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <%= image_tag('91.png', class: 'back_img') %>
      <button class="project_btn mt-3 mb-3">Save</button>
    </div>
  </div>
<% end %>

app/views/time_flow_monitors/_preview_table.html.slim
.col-md-12
  .table-responsive.data_table.mt-3.mb-3
    table.table.monitor_table
      thead.custom-thead
        tr
          th.form_img[colspan="4"]
            h5.mb-0
              | Query Result
      tbody
        tr.border_none
          td[colspan="2" align="right"]
            .data_content
              h6.pt-2.text-left
                | Total Records in Set: #{@total_records}
          td[colspan="1" align="right"]
            span.span_show
              | Show:
            .dropdown.extra_btn
              button#dropdownMenuButton.btn.btn-secondary.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
                |  10
                i.fa.fa-angle-down[aria-hidden="true"]
              .dropdown-menu[aria-labelledby="dropdownMenuButton"]
                a.dropdown-item[href="#"]
                  | 20
                a.dropdown-item[href="#"]
                  | 50
                a.dropdown-item[href="#"]
                  | 100
          td[colspan="1"]
            form
              input[type="search" name="search" placeholder="Search"]
              label
                = image_tag('85.png')
        - if total_records > 1
          tr.thead
            - columns.each do |column|
              th
                span
                  = column.titleize
                i.fa.fa-angle-up[aria-hidden="true"]
          - rows.each do |records|
            tr
              - records.each do |value|
                td
                  = value
  = image_tag('91.png', class: 'back_img')
  a#alert_btn.project_btn.mt-3.mb-3[href="javascript:void(0);"]
    | Alert
  = image_tag('91.png', class: 'back_img', id: 'alert_arrow', style:'display:none')

app/views/time_flow_monitors/edit.html.erb
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12 pb-3">
        <a href="<%= project_time_flow_monitors_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="new_event text-center pt-5">
          <h3 class="pb-4">Edit Monitor</h3>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">


 $("#alert_btn").click(function(){
    $("#alert_table").show();
    $("#alert_arrow").show();
  });
</script>

app/views/time_flow_monitors/event_definitions.js.slim
| $('#event_definition_fields').html("
= j (render partial: 'event_definition_fields', locals: {event_stream: @event_stream})
| ")

app/views/time_flow_monitors/index.html.erb
<% if @time_flow_monitors.blank? %>
  <section class="event_stream">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="event_stream_inner text-center">
            <%= image_tag('monitor-icon.png') %>
            <h3>Monitors</h3>
            <p>No monitors are available.</p>
            <%= link_to 'Add Monitor', new_project_time_flow_monitor_path(@project), class: "project_btn mt-3 white_color_link" %>
          </div>
        </div>
      </div>
    </div>
  </section>
<% else %>
  <section class="event_stream">
      <div class="container">
          <div class="row">
              <div class="col-md-12">
                  <div class="customer_value_exam row">
                      <div class="col-md-1">
                          <%= image_tag('71.png') %>
                      </div>
                      <div class="col-md-6">
                          <h3><%= @project.name %></h3>
                          <p><%= @project.description %></p>
                      </div>
                      <div class="col-md-3 text-right">
                          <p class="pt-4">Owner: <%= current_user.full_name %></p>
                      </div>
                      <div class="col-md-2 text-right pt-1">
                          <ul>
                              <li>
                                  <a href="#"><%= image_tag('74.png') %></a>
                              </li>
                             <li>
                                  <a href="#"><%= image_tag('51.png') %></a>
                              </li>
                              <li>
                                  <a href="#"><%= image_tag('72.png') %></a>
                              </li>
                          </ul>
                      </div>
                  </div>
              </div>
              <div class="col-md-12">
                <div class="border_bottom"></div>
              </div>

              <div class="col-md-12 mt-5">
                <table class="table event_stream">
                  <thead>
                    <tr>
                      <td colspan="3">
                        <h4>Monitors</h4>
                      </td>
                      <td colspan="1">
                        <form>
                          <input type="search" name="search" placeholder="Search">
                          <label><%= image_tag('85.png') %></label>
                        </form>
                      </td>
                    </tr>
                  </thead>
                  <tbody>
                    <% @time_flow_monitors.each do |monitor| %>
                      <tr>
                          <td width="5%">
                            <%= image_tag('Union.png', class: 'img_1') %>
                          </td>
                          <td width="5%">
                            <%= image_tag('75.png', class: 'img_2') %>
                          </td>
                          <td width="50%">
                            <div class="table_content">
                              <% if monitor.description.present? %>
                                <h5 class="mb-0"><%= monitor.name %> </h5>
                                <p class="mb-0"><%= monitor.description %></p>
                              <%else%>
                                <h5 class="margin-15"><%= monitor.name %> </h5>
                              <%end%>
                            </div>
                          </td>
                          <td width="20%">
                            <div class="eye_inner">
                              <% if !monitor.sidekiq_job_id%>
                                <%= link_to start_project_time_flow_monitor_path(@project, monitor), "data-turbolinks": "false" do %>
                                  <%= image_tag('start.png') %>
                                <% end %>
                              <% else %>
                                <%= link_to pause_project_time_flow_monitor_path(@project, monitor), "data-turbolinks": "false" do %>
                                  <%= image_tag('pause.png') %>
                                <% end %>
                              <% end %>

                              <%= link_to edit_project_time_flow_monitor_path(@project, monitor) do %>
                                <%= image_tag('eye.png') %>
                              <% end %>

                              <%= link_to edit_project_time_flow_monitor_path(@project, monitor) do %>
                                <%= image_tag('edit.png', style: 'display: inline-block;') %>
                              <% end %>

                              <%= link_to project_time_flow_monitor_path(@project, monitor), method: :delete, data: { confirm: 'Are you sure?' } do %>
                                <%= image_tag('delete.png') %>
                              <% end %>
                            </div>
                          </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <center>
                  <%= link_to 'Add Monitor', new_project_time_flow_monitor_path(@project), class: "project_btn mt-3 white_color_link align-items-center" %>
                </center>
              </div>
          </div>
      </div>
  </section>
<% end %>

app/views/time_flow_monitors/new.html.erb
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12 pb-3">
        <a href="<%= project_time_flow_monitors_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>
        <div class="new_event text-center pt-5">
          <h3 class="pb-4">New Monitor</h3>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/time_flow_monitors/preview.js.slim
| $('#preview_table').html("
= j (render partial: 'preview_table', locals: {event_stream: @event_stream, rows: @rows, columns: @columns, total_records: @total_records})
| ")