config/routes.rb
# == Route Map
#

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :simulation_steps

  resources :report_items

  get '/event_definitions/:id', to: 'simulations#event_definitions', as: 'event_definitions'
  get '/event_definition_monitor/:id', to: 'time_flow_monitors#event_definitions', as: 'event_definition_monitor'

  resources :projects do
    resources :simulations do
      member do
        get :start
        get :pause
      end
    end
    resources :reports do
      collection do
        get :event_stream_fields
      end
    end
    resources :time_flow_logs
    resources :event_stream_fields
    resources :event_streams do
      collection do
        get :saved_search
        get :external_data_sources
        get :simulations_workflow
        get :time_series
        get :metrics_workflow
      end
    end
    resources :alerts
    resources :time_flow_monitors, path: 'monitors' do
      member do
        get :start
        get :pause
        get :preview
      end

      collection do
        get :preview
      end
    end
    resources :splashes
    resources :datas do
      collection do
        post :set_event_stream
        post :search_results
      end
    end
  end

  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  project_id  :bigint
#
# Indexes
#
#  index_reports_on_project_id  (project_id)
#
class Report < ApplicationRecord
  has_many :report_items, inverse_of: :report, dependent: :destroy
  belongs_to :project

  validates_presence_of :name

  accepts_nested_attributes_for :report_items, reject_if: :all_blank, allow_destroy: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_report, only: %i[ show edit update destroy ]

  # GET /reports or /reports.json
  def index
    @reports = @project.reports
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
    @report.report_items.build
    gon.project_id = @project.id
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)
    @report.project = @project

    respond_to do |format|
      if @report.save
        format.html { redirect_to project_reports_path(@project), notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to project_reports_path(@project), notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to project_reports_path(@project), notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def event_stream_fields
    @event_stream = EventStream.find(params[:event_stream_id])
    @element_number = params[:element_number]
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = @project.reports.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:name, :description, report_items_attributes: [:name, :event_stream_id, 
                                                                                    :duration, :time_period, 
                                                                                    data: {filters: [:field, :operator, :value]}])
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def display_chart(chart_type, data)
    eval("#{chart_type}(#{data})")
  end

  def get_filtered_data(report_item)    
    conditions = []
    report_item.data['filters'].each do |datum|
      conditions << "#{datum['field'].parameterize(separator: '_')} #{datum['operator']} '#{datum['value']}'"
    end

    if report_item.aggregate?
      results = KafkaClickhouse.get_aggregated_data({'time_frame' => 'next', 'duration' => 0, 'field_name' => 'lucy_ward'}, report_item.event_stream)
    else
      results = KafkaClickhouse.search(report_item.event_stream, conditions.join(' AND '))
    end

    return results
  end
  
end

app/views/reports/_event_stream_fields.html.slim
- @event_stream.event_stream_fields.each do |esf|
  tr
    td width="30%" 
      .form-group
        = text_field_tag "report[report_items_attributes][#{element_number}][data][filters][][field]", esf.name, class: 'form-control', id: 'field_name', readonly: true
    td width="20%" 
      .form-group
        = select_tag "report[report_items_attributes][#{element_number}][data][filters][][operator]", options_for_select(ApplicationRecord::SQL_OPERATORS), id: 'event_stream_id', class: 'form-control form-select'
    td width="20%" 
      .form-group
        = text_field_tag "report[report_items_attributes][#{element_number}][data][filters][][value]", "", class: 'form-control', id: 'field_value', placeholder: 'Value'

app/views/reports/_form.html.slim
= simple_form_for [project, report] do |form|
  .row
    - if report.errors.any?
      #error_explanation
        h2
          = pluralize(report.errors.count, "error")
          |  prohibited this report from being saved:
        ul
          - report.errors.each do |error|
            li
              = error.full_message

  .row
    .new_event.text-center.pt-5
      h3.pb-5
        | New Report
      #myTabContent.tab-content
        #home.tab-pane.fade.show.active[role="tabpanel" aria-labelledby="home-tab"]
          .row
            .col-md-6
              .form-group
                = form.text_field :name, class: 'form-control', placeholder: 'Report Name'
                |  <div id="message" style="
                = form.object.errors[:name].present? ? '' : 'display:none;'
                | "> 
                = form.object.errors[:name].first
          .col-md-6
            .form-group
              = form.text_field :description, class: 'form-control', placeholder: 'Report Description'

          .col-md-12#report_items
            = form.fields_for :report_items do |ff|
              .nested-fields.pt-3
                = render partial: 'report_items', locals: {f: ff}
            .links
              = link_to_add_association form, :report_items, render_options: {}, class: 'import_btn mt-4 mb-3 ml-2' do
                i.fa.fa-plus[aria-hidden="true"] 
                | Add Items

          .col-md-12
            .border_final.mt-4
              = form.submit "Save", class: 'project_btn mt-5 mb-5'

app/views/reports/_report_item_fields.html.slim
.table-responsive.mt-4.custom_table.monitor
  table.table
    thead
      tr
        th.form_img colspan="4" 
          form
            = f.text_field :name, class: 'form-control', placeholder: 'Title', type: 'search'
            = image_tag('Vector.png')
    tr
      td colspan="3" 
        h4.text-left.pt-3 Filter
      td align="right" colspan="2"
        .customer_value_exam
          ul
            li
              a[href="#"]
                = image_tag('74.png')
            li
              a[href="#"]
                = image_tag('51.png')
            li.dropdown
              a href="#"
                = image_tag('73.png')
            li
              a[href="#"]
                = image_tag('eye.png')
    tr
      td width="30%" 
        .form-group
          = f.select :event_stream_id, options_for_select(@project.event_streams.pluck(:name, :id)), { prompt: 'Select' }, { class: 'form-control form-select new_report_event_stream' }
      td width="20%" 
        .form-group
          = f.text_field :duration, class: 'form-control', placeholder: 'Duration'
      td width="20%" 
        .form-group
          = f.select :time_period, options_for_select(['Second', 'Minute', 'Hour']), { prompt: 'Select' }, { class: 'form-control form-select' }
    tbody.new_report_event_stream_columns_0
    / - 3.times do
    /   tr
    /     td width="30%" 
    /       .form-group
    /         = text_field_tag "report[report_items_attributes][0][data][field]", "", class: 'form-control', id: 'field_name', placeholder: 'Name'
    /     td width="20%" 
    /       .form-group
    /         = select_tag "report[report_items_attributes][0][data][operator]", options_for_select(ApplicationRecord::SQL_OPERATORS), id: 'event_stream_id', class: 'form-control form-select'
    /     td width="20%" 
    /       .form-group
    /         = text_field_tag "report[report_items_attributes][0][data][value]", "", class: 'form-control', id: 'field_value', placeholder: 'Value'

app/views/reports/_report_items.html.slim
.table-responsive.mt-4.custom_table.monitor
  table.table
    thead
      tr
        th.form_img colspan="4" 
          form
            = f.text_field :name, class: 'form-control', placeholder: 'Title', type: 'search'
            = image_tag('Vector.png')
    tr
      td colspan="3" 
        h4.text-left.pt-3 Filter
      td align="right" colspan="2"
        .customer_value_exam
          ul
            li
              a[href="#"]
                = image_tag('74.png')
            li
              a[href="#"]
                = image_tag('51.png')
            li.dropdown
              a href="#"
                = image_tag('73.png')
            li
              a[href="#"]
                = image_tag('eye.png')
    tr
      td
        .form-group
          = f.text_field :duration, class: 'form-control', placeholder: 'Next'  
      td
        .form-group
          = f.text_field :duration, class: 'form-control', placeholder: 'Duration'
      td 
        .form-group
          = f.select :time_period, options_for_select(ApplicationRecord::TIME_PERIODS), { prompt: 'Select' }, { class: 'form-control form-select' }
    tr
      td 
        .form-group
          = f.select :event_stream_id, options_for_select(@project.event_streams.pluck(:name, :id)), { prompt: 'Select' }, { class: 'form-control form-select new_report_event_stream' }

    tbody#new_report_event_stream_columns_0
    / - 3.times do
    /   = f.fields :data, model: OpenStruct.new(f.object.data) do |field|
    /     tr
    /       td width="30%" 
    /         .form-group
    /           = field.text_field :field, class: 'form-control', id: 'field_name', placeholder: 'Column'
    /       td width="20%" 
    /         .form-group
    /           = field.select :operator, options_for_select(ApplicationRecord::SQL_OPERATORS), {}, { id: 'event_stream_id', class: 'form-control form-select' }
    /       td width="20%" 
    /         .form-group
    /           = field.text_field :value, class: 'form-control', id: 'field_value', placeholder: 'Value'

app/views/reports/edit.html.erb
<!--Event Stream-->
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12 pb-3">
        <a href="<%= project_reports_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>

        <%= render partial: 'form', locals: { project: @project, report: @report } %>
      </div>
    </div>
  </div>
</section>
<!--Event Stream--> 



app/views/reports/event_stream_fields.js.slim
| $("#new_report_event_stream_columns_#{@element_number}").html("
= j (render partial: 'event_stream_fields', locals: { element_number: @element_number, event_stream: @event_stream })
| ")

app/views/reports/index.html.slim
- if @reports.blank?
  section.event_stream
    .container
      .row
        .col-md-12
          = link_to projects_path, class: "back_btn" do
            Back
          .event_stream_inner.text-center
            = image_tag('report-icon.png')
            h3 Reports
            p No reports are available.
            = link_to 'New Report', new_project_report_path(@project), class: 'project_btn mt-3 white_color_link'
- else
  section.event_stream
    .container
      .row
        .col-md-12
          .customer_value_exam.row
            .col-md-1
              = image_tag('71.png')
            .col-md-6
              h3
                = @project.name
              p
                = @project.description
            .col-md-2.text-right
              p.pt-4
                | Owner: 
                = current_user.full_name
            .col-md-3.text-right.pt-1
              ul
                li
                  a[href="#"]
                    = image_tag('74.png')
                li
                  a[href="#"]
                    = image_tag('51.png')
                li
                  a[href="#"]
                    = image_tag('73.png')
                li
                  a[href="#"]
                    = image_tag('72.png')
        .col-md-12
          .border_bottom
        .col-md-12.mt-5
          table.table.event_stream
            thead
              tr
                td[colspan="3"]
                  h4
                    | Reports
                td[colspan="1"]
                  form
                    input[type="search" name="search" placeholder="Search"]
                    label
                      = image_tag('85.png')
            tbody
              - index = 0
              - @reports.each do |report|
                tr
                  td[width="5%"]
                    = image_tag('Union.png', class: 'img_1')
                  td[width="5%"]
                    = image_tag(EventStream::LIST_ICONS[index], class: 'img_2')
                  - index = index == 8 ? 0 : index + 1
                  td[width="50%"]
                    .table_content
                    - if report.description.present?
                      h5.mb-0
                         = report.name
                      p.mb-0
                        = report.description
                    - else
                      h5.margin-15
                        = report.name
                  
                  td[width="20%"]
                    .eye_inner
                      = link_to project_report_path(@project, report) do
                        = image_tag('eye.png', style: 'display: inline-block;')
                      = link_to edit_project_report_path(@project, report) do
                        = image_tag('edit.png', style: 'display: inline-block;')
                      = link_to project_report_path(@project, report), method: :delete, data: { confirm: 'Are you sure?' } do
                        = image_tag('delete.png', style: 'display: inline-block;')
          center
            = link_to 'New Report', new_project_report_path(@project), class: 'project_btn mt-3 white_color_link align-items-center'

app/views/reports/new.html.erb
<!--Event Stream-->
<section class="event_stream">
  <div class="container">
    <div class="row">
      <div class="col-md-12 pb-3">
        <a href="<%= project_reports_path %>" class="back_btn"><i class="fa fa-arrow-left" aria-hidden="true"></i>Back</a>

        <%= render partial: 'form', locals: { project: @project, report: @report } %>
      </div>
    </div>
  </div>
</section>
<!--Event Stream--> 



app/views/reports/show.html.slim
p#notice
  = notice
section.event_stream
  .container
    h3.pb-4.text-center
      = @report.name
    .d-flex.justify-content-center
      ul#myTab.nav.nav-tabs.center[role="tablist"]
        li.nav-item
          a#home-tab.nav-link[data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"]
            | Show
        li.nav-item
          a#profile-tab.nav-link.active[data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"]
            | Edit
    .row.pt-4
      .col-md-12
        - @report.report_items.each do |report_item|
          - next if report_item.event_stream.nil?
          - results = get_filtered_data(report_item)
          .table-responsive.data_table
            table.table
              tr.border_none
                td[colspan="3"]
                  .data_content
                    p.mb-0
                      = report_item.event_stream&.name
                    h6.pb-1
                      | Total Records in Set: #{results.count}
                td[colspan="1" align="right"]
                  span.span_show
                    | Show:
                  .dropdown.extra_btn
                    button#dropdownMenuButton.btn.btn-secondary.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
                      |  10 
                      i.fa.fa-angle-down[aria-hidden="true"]
                    .dropdown-menu[aria-labelledby="dropdownMenuButton"]
                      a.dropdown-item[href="#"]
                        | 20
                      a.dropdown-item[href="#"]
                        | 50
                      a.dropdown-item[href="#"]
                        | 100
                td[colspan="2"]
                  form
                    input[type="search" name="search" placeholder="Search"]
                    label
                      = image_tag('85.png')
              tr.thead
                - results.columns.each do |column|
                  th
                    span
                      = column.titleize
                    i.fa.fa-angle-up[aria-hidden="true"]

              - results.rows.each do |rows|
                tr.col-md-12
                  - rows.each do |row|
                    td.col-md-2
                      = row

              tfoot
                tr
                  td[colspan="3"]
                    p.mb-0
                  td[colspan="4" align="right"]

    - ['column_chart', 'bar_chart', 'line_chart', 'area_chart'].each do |chart|
      .row
        .col-md-12.mt-3
          .row.event_table.thead
            .col-md-2
              | Source Data
          .nested-fields.pt-3.custom-table-new
            .row
              .col-md-5
                .form-group
                  |  Total Records In Set: 3000 
            .row
              .col-md-5
                .form-group
                  = display_chart(chart, Simulation.group(:simulation_type).count)
script[type="text/javascript" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"]
script[type="text/javascript"]
  |  $( document ).on('turbolinks:load', function() { $('#example').DataTable(); } ); 